spring:
  rabbitmq:
    addresses: 192.168.10.16:5672
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        acknowledge-mode: manual  #手动确认
        concurrency: 5      #并发数
        max-concurrency: 10 #最大并发数
        prefetch: 1   #限流
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /
  port: 8002
