spring:
  rabbitmq:
    addresses: 192.168.10.17:5672
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 15000
    publisher-returns: true   #开启消息确认模式
    template:
      mandatory: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.10.17:3306/rabbit_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /
  port: 8001
